version: "3.8"

services:
  app:
    container_name: service
#    image: alexanderbryksin/products_microservice:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - PORT=5000
    restart: always

