version: '3.8'
services:
  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    ports:
      - "9010:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
      image: 'docker.io/bitnami/kafka:2-debian-10'
      ports:
        - '9092'
      environment:
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
      volumes:
        - 'kafka2_data:/bitnami'
      depends_on:
        - zookeeper
    kafka2:
      image: 'docker.io/bitnami/kafka:2-debian-10'
      ports:
        - '9092'
      environment:
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
      volumes:
        - 'kafka_data:/bitnami'
      depends_on:
        - zookeeper
    kafka3:
      image: 'docker.io/bitnami/kafka:2-debian-10'
      ports:
        - '9092'
      environment:
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
      volumes:
        - 'kafka3_data:/bitnami'
      depends_on:
        - zookeeper

volumes:
  kafka_data:
    driver: local
  kafka2_data:
    driver: local
  kafka3_data:
    driver: local