AppVersion: 1.0.0
Server:
  Port: :5555
  Development: true
  Timeout: 15
  ReadTimeout: 5
  WriteTimeout: 5
  MaxConnectionIdle: 5
  MaxConnectionAge: 5

Kafka:
  Brokers: ["localhost:9091", "localhost:9092", "localhost:9093"]
#  Brokers: ["host.docker.internal:9091", "host.docker.internal:9092", "host.docker.internal:9093"]

Logger:
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

Metrics:
  Port: ":7070"
  Url: 0.0.0.0:7071
  ServiceName: products_microservice

Jaeger:
  Host: host.docker.internal:6831
  ServiceName: products_microservice
  LogSpans: false

MongoDB:
  URI: "mongodb://host.docker.internal:27017"
  User: "admin"
  Password: "admin"
  DB: "products"