AppVersion: 1.0.0
Server:
  Port: :5555
  Development: true

Logger:
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

Metrics:
  Url: 0.0.0.0:7071
  ServiceName: user_microservice

Jaeger:
  Host: localhost:6831
  ServiceName: products_microservice
  LogSpans: false